name: ATruax Photography
favicon: null
layout_spectrum: 0.51564
typography_spectrum: 0.70711
title: 'ATruax Photography | San Diego Photographer of Music, Headshots and More'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#fbfbfb'
    - '#606060'
    - '#8e8e8e'
    - '#cdcdcd'
  brandStrength: 0.5
  lightness: 0.6726225870661438
  saturation: 0.3373225722461939
  rhythmicContrast: 0.8986073392443359
purpose: []
