name: ATruax Photography
favicon: null
layout_spectrum: 0.03583232965320349
typography_spectrum: 0.9749809408094734
title: 'ATruax Photography | San Diego Photographer of Music, Headshots and More'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.819671010831371
  lightness: 0.6726225870661438
  saturation: 0.3373225722461939
  rhythmicContrast: 0.8986073392443359
purpose: []
